#METADATA Y DESPUÉS DEFINIMOS UN FICHERO QUE SE LLAMA PROMETHEUS.YAML
#DONDE TENEMOS UN DATASOURCE, DE MOMENTO UNO QUE ES EL QUE VAMOS A INCLUIR
#LO IMPORTANTE ES EL ENDPOINT QUE TIENE QUE COINCIDIR CON EL DE PROMETHEUS, 
#EL NOMBRE DEL SERVICIO Y EL PUERTO INTERNO DENTRO DEL CLUSTER PROMETHEUS 8280
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.monitoring.svc:8280",
                "version": 1
            }
        ]
    }