#LO USAMOS PARA PASAR UN SH QUE CONECTA AL MOTOR DE LA BBDD Y
#CREA UN USUARIO, LA BASE DE DATOS Y QUE LE OTORGUE PRIVILEGIOS
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script-configmap
data:
  initdb.sh: |-
   #!/bin/bash
   set -e
   psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER billingapp WITH PASSWORD 'qwerty';
    CREATE DATABASE billingapp_db;
    GRANT ALL PRIVILEGES ON DATABASE billingapp_db TO billingapp;
   EOSQL