#METADATA, SE ESPECIFICA COMO VA A SER LA RÉPLICA, EL TEMPLATE Y LA IMAGEN DESCAGA DOCKERHUB
#REFERENCIA A VARIABLES PGADMIN-SECRET Y ABRO PUERTO DENTRO DEL CONTENEDOR PARA LA CONECTIVIDAD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4        
          envFrom:
            - secretRef:
                name: pgadmin-secret
          ports:
            - containerPort: 80
              name: pgadminport