#ALMACENAMIENTO PERSISTENTE E INDEPENDIENTE, SE CREA MANUAL LE DOY 5 GIGAS
#ES DE LECTURA Y ESCRITURA Y HACEMOS EL MONTAJE EN MNT/DATA  QUE ES DONDE 
#ALMACENA LA BBDD
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/"