#LA PARTE IMPORTANTE ES LA DEFINICION DONDE SE DICE QUE LA PETICIÓN TOMA DOS GIGAS
#Y QUE VA A TENER ACCESO DE LECTURA Y ESCRITURA DESDE LOS PODS
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi