#IGUAL QUE EL ANTERIOR, SÓLO QUE CAMBIAN LAS VARIABLES, SACADAS DE LA IMAGEN OFICIAL DE PG
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  labels:
    app: postgres
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AYWRtaW4uY29t
  PGADMIN_DEFAULT_PASSWORD: cXdlcnR5
  PGADMIN_PORT: ODA=