#SERVICIO, NOMBRE Y MAPEO DE PUERTOS INTERNO Y EXTERNO 
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
   - port: 80
     nodePort: 30200



     