#CREAMOS AUTORIZACION, UN ROL CON LOS PERMISOS PARA LA PARTE DE MONITORIZACION
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"] # ACCESO A LOS OBJETOS ANTERIORES Y PUEDE HACER LISTAR, VER...
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
#CUALQUIERA QUE PERMITA A ESTE GRUPO DE PERMISOS PUES TENDRÁ ACCESO PARA LAS TAREAS MENCIONADAS ANTERIORMENTE
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: default
  namespace: monitoring