apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
# CONTENEDOR CON IMAGEN DE DOCKERHUB, SE DEFINEN ATRIBUTOS, PUERTOS, RECURSOS DE MEMORIA, LA INSTALACIÓN
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
# MONTAMOS LOS VOLUMENES QUE SERÁN LOS QUE NOS PERMITAN MANTENER LA INFORMACIÓN           
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  
        - name: prometheus-storage-volume
          emptyDir: {}
---
# LA DEFINICIÓN DEL SERVICIO PARA QUE SEA ACCESIBLE FUERA DEL CLUSTER
kind: Service
apiVersion: v1
metadata:
  name: prometheus-service
  namespace: monitoring
  labels:
    app: prometheus-server
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '9090'
spec:  
# PUERTO INTERNO DEL SERVICIO DENTRO DEL CLUSTER, PUERTO EXTERNO Y PUERTO POR DEFECTO DE PROMETHEUS
  ports:
  - name: prometheus-server
    port: 8280
    nodePort : 30000 
    targetPort: 9090
  #type: LoadBalancer
  type: NodePort
  selector:
   app: prometheus-server