#BACKEND CON 3 PODS, NECESITA CONECTARSE CON LA BBDD POSTGRES
#ASIGNAR IP FIJA MÁS EFICIENTE DE COMUNICARSE INDEPENDIENTE DE LAS VECES QUE CAMBIE EL POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-app-back-deployment
spec:
  selector:
   matchLabels:
    app: billing-app-back
  replicas: 3
  template:
    metadata:
      labels:
        app: billing-app-back
    spec:
      containers:
        - name: billing-app-back
          image: oliverp83/facturacionapp-back     
          ports:
            - containerPort: 7080
              name: billingappbport